---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidly-frontend
  template:
    metadata:
      labels:
        app: vidly-frontend
    spec:
      containers:
      - name: vidly-frontend
        image: ${ECR_REGISTRY}/vidly-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidly-backend
  template:
    metadata:
      labels:
        app: vidly-backend
    spec:
      containers:
      - name: vidly-backend
        image: ${ECR_REGISTRY}/vidly-backend:${IMAGE_TAG}
        ports:
        - containerPort: 3001
        env:
        - name: DB_URL
          value: "mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:27017/vidly"
---
apiVersion: v1
kind: Service
metadata:
  name: vidly-frontend
spec:
  selector:
    app: vidly-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vidly-backend
spec:
  selector:
    app: vidly-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP